### ISSUE TITLE
Plus de remonté d'informations depuis l'API

### ISSUE THREAD

**Issue by mlamoitte** [KiboOst/jeedom_docs#1]
Bonjour,

Il y a eu une mise à jour chez Qivivo dans la nuit du 28/03 au 29/03.

Depuis le 29 tous mes équipements me remonte la dernière information reçu avant migration, la fonction "rafraichir" ne change rien.

Exemple
Pour tester l'api,
Si je fais un appel GET avec postman, sur wireless-modules pour obtenir les informations de celle-ci j'obtiens

{
    "currentTimeBetweenCommunication": 5,
    "lastCommunicationDate": "2019-03-28 23:29"
     ...
}

Suis-je le seul dans ce cas ?

D'avance merci

**Comment by KiboOst** [comment]
Désolé je n'avais pas vue vette issue.
Problème bien sûr réglé depuis longtemps, Qivivo n'avait pas migré l'API.
